version: 2
root-markers:
  - .git/
  - go.mod
lint-debounce: 1s
commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

tools:
  golangci-lint: &golangci-lint
    lint-command: 'golangci-lint --fast'
    lint-stdin: true
    format-stdin: true
    format-command: gofumports

  gopls: &gopls
    lint-command: 'gopls'
    lint-stdin: true
    format-stdin: true
    format-command: gofumports

languages:
  go:
    - <<: *gopls
    - <<: *golangci-lint


  =:
    - <<: *any-excitetranslate